version: "3"

services:
  db:
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=citizens
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - dj_postgres_data:/var/lib/postgresql/data/
  jdk:
    image: adoptopenjdk/openjdk11-openj9
  app:
    image: sha256:32ddd5d0a94ad3f861e237115b004092978a3b8fce45ff9a3134ba18406e3106
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  dj_postgres_data:
